### ISSUE TITLE
Timeouts not showing the reason

### ISSUE THREAD

**Issue by k0re** [jctrvlr/twitchPS#14]
The reason is not shown when you receive a timeout message.
The fix is the following last line beginning with reason: in the following code:

      case 'timeout':
        this.emit('timeout', {
          target: message.data.message.data.args[0],
          target_user_id: message.data.message.data.target_user_id,
          created_by: message.data.message.data.created_by,
          created_by_user_id: message.data.message.data.created_by_user_id,
          duration: message.data.message.data.args[1],
          reason: message.data.message.data.args[2] || null,

Would you mind to add that? :) Thanks!

**Comment by jctrvlr** [comment]
Sure will add that in and try to get it out later today after some testing.

**Comment by k0re** [comment]
i can push it if you want that, i've tested it already on my twitchbot, works like a charm.

**Comment by jctrvlr** [comment]
Just published twitchps@1.4.0. Bumped a minor because I added a bunch of previously unsupported chat actions as well as added the reason for timeouts!
