### ISSUE TITLE
Is there a way to create an error event?

### ISSUE THREAD

**Issue by opti21** [jctrvlr/twitchPS#18]
For example: ps.on('error')

**Comment by jctrvlr** [comment]
Not currently the error is just output but emitting an error wouldn't be too difficult, and frankly is a pretty good idea.

**Comment by opti21** [comment]
It would be great to show what triggered the error especially if it's a BAD AUTH. Most likely an expired token so when it triggers a bad auth error I can simply refresh the token then try to re-listen to that specific topic

**Comment by jctrvlr** [comment]
A bit sloppy (went thru a few patch numbers there...) I updated it to output error including a separate topic field is the error involves a specific topic. An example of an error message for bad auth/token would look like - 
```
{
  origin: 'addTopic()',
  error: 'ERR_BADAUTH',
  topic: 'chat_moderator_actions.38290946'
}
```
Let me know if this is adequate or if you think it could be improved further!

**Comment by opti21** [comment]
One suggestion if there's a way to output the channel id specifically that would save time for the end user.
