### ISSUE TITLE
Reconnect does not seem to work

### ISSUE THREAD

**Issue by Lange** [jctrvlr/twitchPS#5]
Hello! :wave:

I have `reconnect: true` and `debug:true` set in the options of the twitchps instance I am creating. I am also logging on the `connected`, `disconnected`, and `reconnect` events. The initial connection is successful, but after about 10 seconds it disconnects, says it is attempting a `reconnect`, and no further action happens. It will not reconnect until I restart the program.

Is there some configuration I am missing? Thanks!

**Comment by Lange** [comment]
Ah! The problem was indeed on my end. I had accidentally made `init_topics` be just an object of the one topic that I wanted, rather than an _array_ containing that topic object. Fixing this coding error resolved the issue.

**Comment by jctrvlr** [comment]
Glad you got it working! I've been meaning to refactor the entire package as I wrote it quite hastily. If there's anything you'd like added to the package or anything you want fixed that you think is broken.
